src/MyPersonalSite/MyPersonalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from blog.views import blog_list

urlpatterns = [
    path('admin/', admin.site.urls),

    # 个人简历
    path('intro/', include('intro.urls', namespace='intro')),

    # 首页
    path('', blog_list, name='home'),

    # 用户
    path('user/', include('user.urls', namespace='user')),

    # 博客
    path('blog/', include('blog.urls', namespace='blog')),

    # 评论
    path('comment/', include('comment.urls', namespace='comment')),

    # 通知（norifications库自带）
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # 通知
    path('notice/', include('notice.urls', namespace='notice')),

    # 第三方登陆，用户注册登陆，密码重置等功能，allauth库
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/MyPersonalSite/blog/urls.py
# Author    :Albert Shen
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_main'),
    path('list/', views.blog_list, name='blog_list'),
    path('detail/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('create/', views.blog_create, name='blog_create'),
    path('delete/<int:blog_id>/', views.blog_delete, name='blog_delete'),
    path('update/<int:blog_id>/', views.blog_update, name='blog_update'),
    path('like/<int:blog_id>/', views.blog_like, name='blog_like'),
    path('first_view/<int:blog_id>/', views.blog_first_view, name='blog_first_view'),
    path('blog_add_picture/', views.blog_add_picture, name='blog_add_picture'),
]

src/MyPersonalSite/homework/urls.py
# Author    :Albert Shen
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'homework'

urlpatterns = [
    path('', views.homework_main, name='homework_main'),
    # 作业列表
    path('list/', views.homework_list, name='homework_list'),
    # 作业详情
    path('detail/<int:homework_id>/', views.homework_detail, name='homework_detail'),
    # 新建作业
    path('create/', views.homework_create, name='homework_create'),
    # 更新作业
    path('update/<int:homework_id>/', views.homework_update, name='homework_update'),
    # 删除作业
    path('delete/<int:homework_id>/', views.homework_delete, name='homework_delete'),
    # 学生提交作业
    path('submit_homework/<int:homework_id>/', views.submit_homework, name='submit_homework'),
    # 查看某次作业某位学生成绩
    path('homework_grade/<int:homework_id>/<int:student_id>/', views.homework_grade, name='homework_grade'),
    # 批改某次作业某位学生作业
    path('mark_homework/<int:homework_id>/<int:student_id>/', views.mark_homework, name='mark_homework'),
    # 查看某班总览
    # path('class/<int:school_class_id>/', views.school_class, name='school_class'),
    # # 查看某班某次作业总览
    # path('class/<int:school_class_id>/homework/<int:homework_id>/', views.school_class_homework, name='school_class_homework'),
    # 查看某次作业总览
    path('homework_overview/<int:homework_id>/', views.homework_overview, name='homework_overview'),

    # 删除大题
    path('delete_big_question/<int:big_question_id>/', views.delete_big_question, name='delete_big_question'),
    # 删除小题
    path('delete_small_question/<int:small_question_id>/', views.delete_small_question, name='delete_small_question'),


    # 添加选择题
    path('create_choice_question/<int:homework_id>/', views.create_choice_question, name='create_choice_question'),
    # 修改选择题
    path('update_choice_question/<int:big_question_id>/', views.update_choice_question, name='update_choice_question'),

    # 修改或添加大题
    path('update_big_question/<int:big_question_or_homework_id>/', views.update_big_question,
         name='update_big_question'),
    # 修改或添加小题
    path('update_small_question/<int:question_id>/', views.update_small_question,
         name='update_small_question'),
]

src/MyPersonalSite/homework/forms.py
# Author    :Albert Shen
# -*- coding: utf-8 -*-

from django import forms

src/MyPersonalSite/homework/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.urls import reverse
from itertools import chain
from operator import attrgetter
from .models import *
from .forms import *
from user.models import SchoolClassPost


# Create your views here.


def homework_list(request):
    search = request.GET.get('search')
    column = request.GET.get('column')

    homework_list = HomeworkPost.objects.all()

    if search:
        homework_list = homework_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    if column is not None and column.isdigit():
        homework_list = homework_list.filter(column=column)

    paginator = Paginator(homework_list, 9)
    page = request.GET.get('page')
    homeworks = paginator.get_page(page)

    context = {
        'homeworks': homeworks,
        'search': search,
    }

    return render(request, 'homework/list.html', context)


def homework_main(request):
    return redirect('homework:homework_list')


def homework_detail(request, homework_id):
    homework = HomeworkPost.objects.get(id=homework_id)
    big_questions = BigQuestionPost.objects.filter(homework=homework_id)
    small_questions = SmallQuestionPost.objects.filter(big_question__homework__id=homework_id)
    choices = ChoicePost.objects.filter(small_question__big_question__homework__id=homework_id)
    answers = AnswerPost.objects.filter(small_question__big_question__homework__id=homework_id,
                                        student=request.user.id)

    context = {
        'homework': homework,
        'big_questions': big_questions,
        'small_questions': small_questions,
        'choices': choices,
        'answers': answers,
    }
    return render(request, 'homework/detail.html', context)


@login_required(login_url='/user/login/')
def homework_create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        column = request.POST.get('column')
        instrument = request.POST.get('instrument')
        total_time_minute = int(request.POST.get('total_time_minute'))

        if title == '':
            return HttpResponse('标题不能为空')
        if total_time_minute < 0:
            return HttpResponse('完成时间不能小于0')

        HomeworkPost(teacher=request.user, title=title,
                     column=HomeworkColumn.objects.get(id=column),
                     instrument=instrument, total_time_minute=total_time_minute).save()
        return redirect('homework:homework_list')
    else:
        columns = HomeworkColumn.objects.all()
        context = {
            'columns': columns
        }
        return render(request, 'homework/update_homework.html', context)


@login_required(login_url='/user/login/')
def homework_update(request, homework_id):
    homework = HomeworkPost.objects.get(id=homework_id)
    if request.method == 'POST':
        title = request.POST.get('title')
        column = request.POST.get('column')
        instrument = request.POST.get('instrument')
        total_time_minute = int(request.POST.get('total_time_minute'))

        if title == '':
            return HttpResponse('标题不能为空')
        if total_time_minute < 0:
            return HttpResponse('完成时间不能小于0')

        homework = HomeworkPost.objects.get(id=homework_id)
        homework.title = title
        homework.column = HomeworkColumn.objects.get(id=column)
        homework.instrument = instrument
        homework.total_time_minute = total_time_minute
        homework.save()
        return redirect('homework:homework_list')
    else:
        columns = HomeworkColumn.objects.all()
        context = {
            'columns': columns,
            'homework': homework
        }
        return render(request, 'homework/update_homework.html', context)


@login_required(login_url='/user/login/')
def homework_add_class(request):
    if request.method == 'POST':
        return
    elif request.method == 'GET':
        return
    else:
        return



@login_required(login_url='/user/login/')
def homework_delete(request, homework_id):
    if request.method == 'POST':
        homework = HomeworkPost.objects.get(id=homework_id)
        if request.user != homework.teacher:
            return JsonResponse({
                "code": "No",
                "message": "抱歉，你无权删除此题。"
            })
        homework.delete()
        return JsonResponse({
            "code": "Yes",
            "new_href": reverse('homework:homework_list')
        })
    else:
        return JsonResponse({
            "code": "No",
            "message": "仅允许post请求。"
        })


def calculate_total_grade(homework_id, student_id):
    answers = AnswerPost.objects.filter(small_question__big_question__homework=homework_id,
                                        student=student_id).values('final_grade')
    total_grade = 0
    for answer in answers:
        total_grade = total_grade + answer['final_grade']
    return total_grade


def auto_check_answer(homework_id, student_id):
    answers = AnswerPost.objects.filter(small_question__big_question__homework=homework_id,
                                        student=student_id)

    for answer in answers:
        small_question = SmallQuestionPost.objects.get(id=answer.small_question.id)
        if answer.answer_text == small_question.reference_answer:
            answer.final_grade = small_question.score
        else:
            answer.final_grade = 0
        answer.save()

    grade = GradePost.objects.get(student=student_id, homework=homework_id)
    grade.final_grade = calculate_total_grade(homework_id, student_id)
    grade.save()
    return


@login_required(login_url='/user/login/')
def submit_homework(request, homework_id):
    if request.method == 'POST':
        student = request.user
        for answer in request.POST.lists():
            if answer[0].isdigit():
                small_question = SmallQuestionPost.objects.get(id=int(answer[0]))
                if AnswerPost.objects.filter(small_question=small_question.id,
                                             student=student.id):
                    new_answer = AnswerPost.objects.get(small_question=small_question.id,
                                                        student=student.id)
                    new_answer.answer_text = answer[1][0]
                    new_answer.save()
                else:
                    new_answer = AnswerPost(small_question=small_question,
                                            student=student,
                                            answer_text=answer[1][0])
                    new_answer.save()
        if not GradePost.objects.filter(student=student.id, homework=homework_id):
            grade = GradePost(student=User.objects.get(id=student.id),
                              homework=HomeworkPost.objects.get(id=homework_id))
            grade.save()
        auto_check_answer(homework_id, student.id)
        return redirect('homework:homework_list')
    else:
        return HttpResponse('仅支持POST请求。')


@login_required(login_url='/user/login/')
def mark_homework(request, homework_id, student_id):
    if request.method == 'POST':
        for mark_grade in request.POST.lists():
            if mark_grade[0].isdigit():
                answer = AnswerPost.objects.get(small_question=int(mark_grade[0]), student=student_id)
                answer.final_grade = int(mark_grade[1][0])
                answer.save()
        if GradePost.objects.filter(student=student_id, homework=homework_id):
            grade = GradePost.objects.get(student=student_id, homework=homework_id)
        else:
            grade = GradePost(student=User.objects.get(id=student_id),
                              homework=HomeworkPost.objects.get(id=homework_id))
        grade.final_grade = calculate_total_grade(homework_id, student_id)
        grade.save()

        return redirect(reverse('homework:homework_overview', args=[homework_id]))
    elif request.method == 'GET':
        student = User.objects.get(id=student_id)
        homework = HomeworkPost.objects.get(id=homework_id)
        answers = AnswerPost.objects.filter(small_question__big_question__homework=homework_id,
                                            student=student_id)
        context = {
            'student': student,
            'homework': homework,
            'answers': answers
        }
        return render(request, 'homework/mark_student_homework_grade.html', context)


@login_required(login_url='/user/login/')
def homework_grade(request, homework_id, student_id):
    if request.method == 'GET':
        student = User.objects.get(id=student_id)
        homework = HomeworkPost.objects.get(id=homework_id)
        answers = AnswerPost.objects.filter(small_question__big_question__homework=homework_id,
                                            student=student_id)
        total_grade = GradePost.objects.get(student=student_id, homework=homework_id)
        context = {
            'student': student,
            'homework': homework,
            'answers': answers,
            'total_grade': total_grade
        }
        return render(request, 'homework/student_homework_grade.html', context)
    else:
        return HttpResponse('仅支持GET请求。')


@login_required(login_url='/user/login/')
def school_class_homework(request, school_class_id, homework_id):
    if request.method == 'GET':
        grades = GradePost.objects.filter(student__profile__school_class=school_class_id,
                                          homework=homework_id)
        school_class = SchoolClassPost.objects.get(id=school_class_id)
        context = {
            'grades': grades,
            'school_class': school_class
        }

src/MyPersonalSite/templates/homework/create_reading_comprehension_question.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 添加阅读理解 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-9">
            <br>
            <form method="post" action="." enctype="multipart/form-data" id="upload_form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="number">题目序号</label>
                    <input type="text" class="form-control" id="number" name="number" value="{{ big_question.number }}">
                </div>

                <div class="form-group">
                    <label for="essay">文章</label>
                    <textarea type="text" class="form-control" id="essay" name="essay" rows="12">{{ big_question.essay }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary" style="display:none;" id="submit">完成</button>
            </form>
        </div>
        <div class="col-3">
            <div type="button" class="btn btn-primary" onclick="submit()">添加问题</div>
        </div>
    </div>
</div>
<script>
    function submit() {
        $('#submit').click();
    }
</script>
{% endblock content %}

src/MyPersonalSite/templates/homework/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    作业详情
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="col-9">

                <h2 align="center">
                    {{ homework.title }}
                </h2>

                <div class="col-12 alert alert-success">说明：
                    {% if homework.instrument %}
                        {{ homework.instrument }}
                    {% else %}
                        无
                    {% endif %}
                    {% if user == homework.teacher %}
                        · <a href="#" onclick="confirm_delete('{% url 'homework:homework_delete' homework.id %}')">删除此作业</a>
                        · <a href="{% url 'homework:homework_update' homework.id %}">修改作业说明</a>
                    {% endif %}
                </div>

                <div class="row mt-2 col-12">
                    {% if big_questions %}
                        <form method="post" action="{% url 'homework:submit_homework' homework.id %}" enctype="multipart/form-data" class="col-12">
                            {% csrf_token %}
                    {% endif %}
                    {% for big_question in big_questions %}
                        {% if big_question.kind == 'SingleChoice' %}
                            {% for small_question in small_questions %}
                                {% if small_question.big_question == big_question %}
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>{{ big_question.number }}.{{ small_question.stem }}</h5>
                                            {% if user == homework.teacher %}
                                                · <a href="#" onclick="confirm_delete('{% url 'homework:delete_big_question' big_question.id %}')">删除此题</a>
                                                · <a href="{% url 'homework:update_choice_question' big_question.id %}">修改此题</a>
                                            {% elif user.profile.is_student %}
                                                <input type="text" class="form-control col-3" id="{{ small_question.id }}" name="{{ small_question.id }}"
                                                       {% for answer in answers %}
                                                           {% if answer.small_question == small_question %}
                                                               value="{{ answer.answer_text }}"
                                                           {% endif %}
                                                       {% endfor %}
                                                       >
                                            {% endif %}
                                        </div>
                                        <div class="card-body">
                                        {% for choice in choices %}
                                            {% if choice.small_question == small_question %}
                                                <div class="card-text">·{{ choice.choice_stem }}.{{ choice.choice_text }}</div>
                                            {% endif %}
                                        {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            <div class="card">
                                {% if big_question.essay %}
                                    {% if user == homework.teacher %}
                                        <div class="card-header">
                                            · <a href="#" onclick="confirm_delete('{% url 'homework:delete_big_question' big_question.id %}')">删除此大题</a>
                                            · <a href="{% url 'homework:update_big_question' big_question.id %}">修改大题文章</a>
                                        </div>
                                    {% endif %}
                                    <div class="card-body">
                                        <p align="justify">{{ big_question.essay|linebreaksbr }}</p>
                                    </div>
                                {% endif %}
                                {% for small_question in small_questions %}
                                    {% if small_question.big_question == big_question %}
                                        <div class="card-header">
                                            <h5>{{ big_question.number|add:small_question.number_offset }}.{{ small_question.stem }}</h5>
                                            {% if user == homework.teacher %}
                                                · <a href="#" onclick="confirm_delete('{% url 'homework:delete_small_question' small_question.id %}')">删除此小题</a>
                                                · <a href="{% url 'homework:update_small_question' small_question.id %}">修改此小题</a>
                                            {% elif user.profile.is_student %}
                                                <input type="text" class="form-control col-3" id="{{ small_question.id }}" name="{{ small_question.id }}"
                                                        {% for answer in answers %}
                                                            {% if answer.small_question == small_question %}
                                                                value="{{ answer.answer_text }}"
                                                            {% endif %}
                                                        {% endfor %}
                                                >
                                            {% endif %}
                                        </div>
                                        <div class="card-body">
                                            {% for choice in choices %}
                                                {% if choice.small_question == small_question %}
                                                    <div class="card-text">{{ choice.choice_stem }}.{{ choice.choice_text }}</div>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <br>
                    {% endfor %}
                    {% if user.profile.is_student and big_questions and user != homework.teacher %}
                            <button type="submit" class="btn btn-primary">提交作业</button>
                        </form>
                    {% endif %}
                </div>
            </div>
            <div class="col-3">
                {% if user == homework.teacher %}
                    <div>· <a href="{% url 'homework:create_choice_question' homework.id %}">添加选择题</a></div>
                    <div>· <a href="{% url 'homework:update_big_question' homework.id %}?is_created=1">添加阅读理解题</a></div>
                    <div>· <a href="{% url 'homework:update_big_question' homework.id %}?is_created=1">添加完形填空题</a></div>
                {% elif user.profile.is_student %}
                    <div>
                        开始时间戳
                        <div id="start_time"></div>
                    </div>
                    <div>
                        当前时间戳
                        <div id="now_time"></div>
                    </div>
                    <div>离考试结束还有</div>
                {% endif %}
            </div>
        </div>
    </div>

    <script>
        function confirm_delete(delete_url) {
            layer.open({
                title: "确认删除",
                content: "此操作不可逆，请谨慎操作",
                yes: function(index, layero) {
                    $.ajax({
                        type: "POST",
                        url: delete_url,
                        data: {
                            "csrfmiddlewaretoken": document.getElementsByName('csrfmiddlewaretoken')[0].value
                        },
                        dataType: "JSON",
                        success: function(result) {
                            if(result.code === 'Yes'){
                                window.location.href=result.new_href;
                            } else{
                                alert(result.message);
                            }
                        }
                    })
                    layer.close(index);
                }
            })
        }

        var time_start = 0;
        var time_now = 0;
        var total_time = {{ homework.total_time_minute }} * 60;

        function start_exam() {
            $.ajax({
                type: "GET",
                url: {% url 'get_time' %},
                data: {
                },
                dataType: "JSON",
                success: function(result) {
                    time_start = result.time;
                    document.getElementById('start_time').innerHTML = time_start;
                }
            })
        }

        function count_down() {
            start_exam();
            var set = setInterval(function() {
                $.ajax({
                    type: "GET",
                    url: {% url 'get_time' %},
                    data: {
                    },
                    dataType: "JSON",
                    success: function(result) {
                        time_now = result.time;
                        document.getElementById('now_time').innerHTML = time_now;
                    }
                })
            }, 1000);
        }

    </script>
{% endblock content %}

src/MyPersonalSite/templates/homework/homework_overview.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    作业总览
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-9">
                <div class="tab-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>学生姓名</th>
                                <th>得分</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for grade in grades %}
                                <tr>
                                    <td>{{ grade.student.username }}</td>
                                    <td>{{ grade.final_grade }}</td>
                                    <td>
                                        <a href="{% url 'homework:mark_homework' grade.homework.id grade.student.id %}">阅卷</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>

    </script>
{% endblock content %}

src/MyPersonalSite/templates/homework/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    答题系统
{% endblock title %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text" class="form-control mb-2 mr-sm-2" name="search"
                    placeholder="搜索题目..." required>
            </form>
        </div>
    </div>

    {% if search %}
        {% if homeworks %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}

    <div class="row mt-2">
        {% for homework in homeworks %}

            <div class="col">
                {% if homework.column %}
                    <a href="{% url 'homework:homework_list' %}?column={{ homework.column.id }}"
                       role="button" class="btn btn-sm hvr-pop btn-outline-secondary">
                        {{ homework.column }}
                    </a>
                {% endif %}

                <h4>
                    <b>
                        <a href="{% url 'homework:homework_detail' homework.id %}"
                           style="color: black;">
                            {{ homework.title }}
                        </a>
                    </b>
                    {% if homework.teacher == user or user.is_superuser %}
                        <a href="{% url 'homework:homework_overview' homework.id %}">作业完成情况总览</a>
                    {% endif %}
                </h4>

                <div>
                    <p style="color: gray;">
                        {{ homework.instrument|slice:'100' }}
                    </p>
                </div>

                <p>
                    <span style="color: blue;">
                        {{ homework.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: darkred;">
                        {{ homework.updated|date:'Y-m-d' }} 更新
                    </span>
                </p>
            </div>
            <hr style="width: 100%;"/>
        {% endfor %}
    </div>

    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                {% if homeworks.has_previous %}
                    <a href="?page=1&search={{ search }}&column={{ column }}" class="btn btn-success">&laquo; 1</a>
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ homeworks.previous_page_number }}&search={{ search }}&column={{ column }}" class="btn btn-secondary">
                        {{ homeworks.previous_page_number }}
                    </a>
                {% endif %}

                <span class="current btn btn-danger btn-lg">
                    {{ homeworks.number }}
                </span>

                {% if homeworks.has_next %}
                    <a href="?page={{ homeworks.next_page_number }}&search={{ search }}&column={{ column }}" class="btn btn-secondary">
                        {{ homeworks.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ homeworks.paginator.num_pages }}&search={{ search }}&column={{ column }}" class="btn btn-success">
                        {{ homeworks.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock content %}

src/MyPersonalSite/templates/homework/school_class_homework.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    班级作业总览
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-9">
                <h5>班级名称：{{ school_class.name }}</h5>
                <div class="tab-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>学生姓名</th>
                                <th>得分</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for grade in grades %}
                                <tr>
                                    <td>{{ grade.student.username }}</td>
                                    <td>{{ grade.final_grade }}</td>
                                    <td>
                                        <a href="{% url 'homework:mark_homework' grade.homework.id grade.student.id %}">阅卷</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>

    </script>
{% endblock content %}