src/MyPersonalSite/MyPersonalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from blog.views import blog_list

urlpatterns = [
    path('admin/', admin.site.urls),

    # 个人简历
    path('intro/', include('intro.urls', namespace='intro')),

    # 首页
    path('', blog_list, name='home'),

    # 用户
    path('user/', include('user.urls', namespace='user')),

    # 博客
    path('blog/', include('blog.urls', namespace='blog')),

    # 评论
    path('comment/', include('comment.urls', namespace='comment')),

    # 通知（norifications库自带）
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # 通知
    path('notice/', include('notice.urls', namespace='notice')),

    # 第三方登陆，用户注册登陆，密码重置等功能，allauth库
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/MyPersonalSite/blog/urls.py
# Author    :Albert Shen
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_main'),
    path('list/', views.blog_list, name='blog_list'),
    path('detail/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('create/', views.blog_create, name='blog_create'),
    path('delete/<int:blog_id>/', views.blog_delete, name='blog_delete'),
    path('update/<int:blog_id>/', views.blog_update, name='blog_update'),
    path('like/<int:blog_id>/', views.blog_like, name='blog_like'),
    path('first_view/<int:blog_id>/', views.blog_first_view, name='blog_first_view'),
    path('blog_add_picture/', views.blog_add_picture, name='blog_add_picture'),
]

src/MyPersonalSite/notice/urls.py
# Author    :Albert Shen
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.comment_notice_list, name='comment_notice_list'),
    # 更新通知状态
    path('update/', views.comment_notice_update, name='comment_notice_update'),
]

src/MyPersonalSite/notice/models.py
from django.db import models

# Create your models here.

src/MyPersonalSite/notice/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse


@login_required(login_url='/accounts/login/')
def comment_notice_list(request):
    notices_unread = request.user.notifications.unread()
    notices_read = request.user.notifications.read()
    context = {
        'notices_unread': notices_unread,
        'notices_read': notices_read
    }
    return render(request, 'notice/list.html', context)


@login_required(login_url='/accounts/login/')
def comment_notice_update(request):
    notice_id = request.GET.get('notice_id')
    if notice_id:
        blog_id = request.GET.get('blog_id')
        request.user.notifications.get(id=notice_id).mark_as_read()
        return redirect(reverse('blog:blog_detail', args=[blog_id]))
    else:
        request.user.notifications.mark_all_as_read()
        return redirect('notice:comment_notice_list')

src/MyPersonalSite/templates/notice/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    {{ user.username }}的通知_Albert 的个人网站
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-4 ml-4">
        <a href="{% url "notice:comment_notice_update" %}" class="btn btn-warning" role="button">标记所有通知为已读</a>
    </div>

    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {% for notice_unread in notices_unread %}
                <li class="list-group-item" id="notice_link">
                    <a href="{% url "notice:comment_notice_update" %}?blog_id={{ notice_unread.target.id }}&notice_id={{ notice_unread.id }}#comment_elem_{{ notice_unread.action_object.id }}"
                       target="_blank"
                    >
                    <span style="color: #5897fb;">
                        {{ notice_unread.actor }}
                    </span>
                        在 <span style="color: #01a252;">{{ notice_unread.target }}</span> {{ notice_unread.verb }}
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice_unread.timestamp|date:"Y/m/d H:i" }}
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="row mt-4 ml-4">
        <div class="btn btn-warning">已读通知</div>
    </div>

    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {% for notice_read in notices_read %}
                <li class="list-group-item" id="notice_link">
                    <a href="{% url "notice:comment_notice_update" %}?blog_id={{ notice_read.target.id }}&notice_id={{ notice_read.id }}#comment_elem_{{ notice_read.action_object.id }}"
                       target="_blank"
                    >
                    <span style="color: #5897fb;">
                        {{ notice_read.actor }}
                    </span>
                        在 <span style="color: #01a252;">{{ notice_read.target }}</span> {{ notice_read.verb }}
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice_read.timestamp|date:"Y/m/d H:i" }}
                </li>
            {% endfor %}
        </ul>
    </div>

</div>

<style>
    #notice_link a:link {
        color: black;
    }

    #notice_link a:visited {
        color: lightgrey;
    }
</style>
{% endblock content %}