src/MyPersonalSite/MyPersonalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from blog.views import blog_list

urlpatterns = [
    path('admin/', admin.site.urls),

    # 个人简历
    path('intro/', include('intro.urls', namespace='intro')),

    # 首页
    path('', blog_list, name='home'),

    # 用户
    path('user/', include('user.urls', namespace='user')),

    # 博客
    path('blog/', include('blog.urls', namespace='blog')),

    # 评论
    path('comment/', include('comment.urls', namespace='comment')),

    # 通知（norifications库自带）
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # 通知
    path('notice/', include('notice.urls', namespace='notice')),

    # 第三方登陆，用户注册登陆，密码重置等功能，allauth库
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/MyPersonalSite/blog/urls.py
# Author    :Albert Shen
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_main'),
    path('list/', views.blog_list, name='blog_list'),
    path('detail/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('create/', views.blog_create, name='blog_create'),
    path('delete/<int:blog_id>/', views.blog_delete, name='blog_delete'),
    path('update/<int:blog_id>/', views.blog_update, name='blog_update'),
    path('like/<int:blog_id>/', views.blog_like, name='blog_like'),
    path('first_view/<int:blog_id>/', views.blog_first_view, name='blog_first_view'),
    path('blog_add_picture/', views.blog_add_picture, name='blog_add_picture'),
]

src/MyPersonalSite/notice/urls.py
# Author    :Albert Shen
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.comment_notice_list, name='comment_notice_list'),
    # 更新通知状态
    path('update/', views.comment_notice_update, name='comment_notice_update'),
]

src/MyPersonalSite/user/urls.py
# Author    :Albert Shen
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login_validate/', views.login_validate, name='login_validate'),
    path('signup_validate/', views.signup_validate, name='signup_validate'),
    path('edit/<int:id>', views.profile_edit, name='profile_edit'),
]

src/MyPersonalSite/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="{% static 'custom/css/base.css' %}">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          crossorigin="anonymous"
    >
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    <script src="{% static 'headroom/headroom.min.js' %}"></script>
    <script src="{% static 'custom/js/base.js' %}"></script>
</head>

<body>
    {% include 'header.html' %}

    <style>
        html, body {
          height: 100%;
        }
        body {
          display: flex;
          flex-direction: column;
        }
        .content {
          flex: 1 0 auto;
        }
        .footer {
          flex-shrink: 0;
        }
    </style>

    <div class="content">
        {% block content %}{% endblock content %}
    </div>

    {% include 'footer.html' %}

    {% block script %}{% endblock script %}
</body>

</html>

src/MyPersonalSite/templates/error.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Error {% endblock title %}

{% block content %}
<div class="container">
    <div class="row errorpage">
        <div class="col align-self-center error-img text-center">
            <div class="errorimg">
                <img class="img-fluid" src="{% static 'image/404.png'%}">
            </div>
            <div class="errormsg">
                <h3>{{ error_message }}</h3>
                <a href="javascript:history.go(-1);">返回地球</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/MyPersonalSite/templates/footer.html
{% load staticfiles %}

<!--回到顶部按钮-->
<div class="text-center" id="to-top">
    <i class="fa fa-chevron-up" id="btn-top" title="回到顶部"></i>
</div>

<nav class="navbar navbar-dark bg-dark mb-0 footer">
    <div class="row col-12 justify-content-center">
        <div style="text-align: center; color: lightgrey;">
            <p class="mb-0">CopyRight © 2020 Albert 的个人网站</p>
        </div>
    </div>
</nav>

src/MyPersonalSite/templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<nav class="navbar navbar-expand-md bg-white fixed-top blog-navbar py-md-0 headroom">
    <a class="navbar-brand d-lg-block" id="site-logo-name" href="/">
        <strong class="px-2">Albert 的个人网站</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-align-justify"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
{#            文章导航#}
            <li class="nav-item mr-2">
                {% url 'blog:blog_list' as list_url %}
                <a class="quiet nav-link py-md-3 {% if request.path == list_url %}active{% endif %}" href="{{ list_url }}">
                    <i class="fa fa-home mr-1"></i>
                    文章
                </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="quiet nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if unread_count %}
                    <svg viewBox="0 0 8 8" width="8px" height="8px">
                        <circle cx="4" cy="4" r="4" fill="#ff6b6b"></circle>
                    </svg>
                    {% endif %}
                    {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href='{% url "user:profile_edit" user.id %}'>个人信息</a>
                    <a class="dropdown-item" href="{% url "notice:comment_notice_list" %}">通知
                    {% if unread_count %}
                    <span class="badge badge-danger">{{ unread_count }}</span>
                    {% endif %}
                    </a>
                    {% if user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'blog:blog_create' %}">写文章</a>
                    {% endif %}
                    <a class="dropdown-item" href='{% url "account_logout" %}'>退出登录</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link quiet" href="{% url 'account_login' %}?next={{ request.path }}">登录</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>